id: I9CE49CB5
legacy_id: P009484
ocr_import_info:
  bdrc_scan_id: W00EGS1016800
  source: bdrc
  ocr_info:
    timestamp: '2020-03-28T08:51:36'
    imagesfolder: images
  batch_id: batch001
  software_id: vision
  expected_default_language: bo
  op_import_options: {}
  op_import_version: 1.0.0
default_language: bo
source: https://library.bdrc.io
source_file: null
initial_creation_type: ocr
imported: '2022-08-30T13:29:21.618214+00:00'
last_modified: 2022-08-30 21:29:42.619802
parser: https://github.com/OpenPecha/Toolkit/blob/7f57883d84bc10351527a49ee6ce970ace404e50/openpecha/formatters/google_ocr.py
source_metadata:
  id: http://purl.bdrc.io/resource/W00EGS1016800
  status: http://purl.bdrc.io/admindata/StatusReleased
  access: http://purl.bdrc.io/admindata/AccessOpen
  reproduction_of: http://purl.bdrc.io/resource/MW00EGS1016800
  copyright_status: http://purl.bdrc.io/resource/CopyrightPublicDomain
  title: གངས་ཅན་འདིར་སྟོན་པའི་རྒྱལ་ཚབ་དཔལ་སྒམ་པོ་པའི་ཁྲི་གདུང་འཛིན་པའི་དམ་པ་རྣམས་ཀྱི་གཏམ་བཻ་ཌཱུ་རྱའི་ཕྲེང་བ།
  author: སྒམ་པོ་མི་ཕམ་ཆོས་ཀྱི་དབང་ཕྱུག
statistics:
  ocr_word_mean_confidence_index: 0.5358729567206191
  ocr_word_median_confidence_index: 0.5099999904632568
quality: null
bases:
  I00EGS1016833:
    source_metadata:
      id: http://purl.bdrc.io/resource/I00EGS1016833
      total_pages: 168
      volume_number: 1
      volume_pages_bdrc_intro: 2
    order: 1
    base_file: I00EGS1016833.txt
    statistics:
      ocr_word_median_confidence_index: 0.5099999904632568
      ocr_word_mean_confidence_index: 0.5358729567206191
    legacy_id: v001
copyright:
  status: Public domain
  notice: Public domain
  info_url: https://creativecommons.org/publicdomain/mark/1.0/
license: CC0
