id: P009484
initial_creation_type: ocr
source_metadata:
  id: bdr:W00EGS1016800
  title: གངས་ཅན་འདིར་སྟོན་པའི་རྒྱལ་ཚབ་དཔལ་སྒམ་པོ་པའི་ཁྲི་གདུང་འཛིན་པའི་དམ་པ་རྣམས་ཀྱི་གཏམ་བཻ་ཌཱུ་རྱའི་ཕྲེང་བ
  author: ''
  volumes: {}
