id: P009484
initial_creation_type: ocr
created_at: 28/03/2020
last_modified_at: 2021-12-19 19:40:52.799481
source_metadata:
  id: bdr:W00EGS1016800
  title: གངས་ཅན་འདིར་སྟོན་པའི་རྒྱལ་ཚབ་དཔལ་སྒམ་པོ་པའི་ཁྲི་གདུང་འཛིན་པའི་དམ་པ་རྣམས་ཀྱི་གཏམ་བཻ་ཌཱུ་རྱའི་ཕྲེང་བ
  author: ''
  volumes:
    1f042c77ed254a878377c07bb2019613:
      image_group_id: I00EGS1016833
      title: ''
      volume_number: 1
      total_pages: 168
      base_file: v001.txt
  access: http://purl.bdrc.io/admindata/AccessOpen
  restrictedInChina: false
